name: Build

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BUILD_TAG: 0

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v1

    - name: Checkout submodules
      run: |
        # Instead of recursively cloning the repo, I manually checkout each submodule as required
        # TinyUSB is a huge repo otherwise.
        git submodule init src/teensy41/USBHost_t36
        git submodule init src/printf
        git submodule init src/tinyusb
        git submodule update
        cd src/tinyusb
        git submodule init hw/mcu/nxp
        git submodule update

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        export BUILD_TAG=build-$(date -u +'%Y%m%d%H%M')
        echo "::set-env name=BUILD_TAG::$BUILD_TAG"

    - name: Run PlatformIO
      run: platformio run -e teensy41

    - if: github.event_name == 'push' 
      name: Create Release
      id: create_release
      uses: "actions/create-release@v1"
      with:
        tag_name: ${{ env.BUILD_TAG }}
        release_name: ${{ env.BUILD_TAG }}
        draft: false
        prerelease: false

    - if: github.event_name == 'push' 
      name: Upload binary to release
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .pio/build/teensy41/firmware.hex
          asset_name: firmware-teensy41.hex
          asset_content_type: application/hex
