name: Build

on:
  push:
    branches: [master]

jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BUILD_TAG: 0

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Checkout submodules
      run: |
        git submodule init lib/USBHost_t36
        git submodule init src/printf
        git submodule init src/tinyusb
        git submodule update
        cd src/tinyusb
        git submodule init hw/mcu/nxp
        git submodule update
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        export BUILD_TAG=build-$(date -u +'%Y%m%d%H%M')
        echo "::set-env name=BUILD_TAG::$BUILD_TAG"
    - name: Run PlatformIO
      run: platformio run -e teensy41
    - name: Create Release
      id: create_release
      uses: "actions/create-release@v1"
      with:
        tag_name: ${{ env.BUILD_TAG }}
        release_name: ${{ env.BUILD_TAG }}
        draft: false
        prerelease: false
    - name: Upload binary to release
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .pio/build/teensy41/firmware.hex
          asset_name: firmware-teensy41.hex
          asset_content_type: application/hex

