name: Pull Request

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Checkout submodules
      run: |
        # Instead of recursively cloning the repo, I manually checkout each submodule as required
        # TinyUSB is a huge repo otherwise.
        git submodule init lib/USBHost_t36
        git submodule init src/printf
        git submodule init src/tinyusb
        git submodule update
        cd src/tinyusb
        git submodule init hw/mcu/nxp
        git submodule update

    - name: Set up Python
      uses: actions/setup-python@v1
  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
  
    - name: Run PlatformIO
      run: platformio run -e teensy41
